language: java

jdk:
  - openjdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
# Added comment - 
